// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ModalTaskController from "./modal_task_controller"
application.register("modal-task", ModalTaskController)

import ModalMissionController from "./modal_mission_controller"
application.register("modal-mission", ModalMissionController)

import ModalSearchController from "./modal_search_controller"
application.register("modal-search", ModalSearchController)

import Select2Controller from "./select2_controller"
application.register("select2", Select2Controller)

import FormTaskController from "./form_task_controller"
application.register("form-task", FormTaskController)

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)
