:concurrency: 5

:queues:
  - default

:scheduler:
  :schedule:
    close_stale_tasks:
      cron: '0 8 * * *'   # каждый день в 08:00
      class: CloseStaleTasksJob
      queue: default
    check_assigment_due:
      cron: '0 9 * * *'   # каждый день в 09:00
      class: CheckAssignmentsDueJob
      queue: default