# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# Department.create(name: 'Офис') unless Department.present?
# department = Department.first
# department.sub_departments.create(name: 'Администрация') unless SubDepartment.present?

# sub_department = SubDepartment.first

# Position.create(name: 'Администратор')
# Position.create(name: 'Электрик')
# Position.create(name: 'Инженер-техник')
# position = Position.first


# Division.create(name: 'Офис', department: department, address: 'г.Казань', email: 'office@mail.ru') unless Division.present?

# User.create(email: 'fd@mail.ru', type_role: 'admin', password: 'Kzn2021$') unless User.present?

# user = User.first

# user.build_profile(full_name: 'Администратор', mobile: '+79274000000', 
#                    sub_department_id: sub_department.id, 
#                    position_id: position.id)
# user.save

# Priority.create(name: 'Высокая', limit_day: 3)
# Priority.create(name: 'Обычная', limit_day: 7)
# Priority.create(name: 'Срочно', limit_day: 1)

# Department.create(name: 'Торговый объект')
# Department.create(name: 'Прочее')
# department = Department.first
# department.sub_departments.create(name: 'Технический отдел')
# department.sub_departments.create(name: 'Финансовый отдел')
# department.sub_departments.create(name: 'IT отдел')
# department.sub_departments.create(name: 'Отдел развития')
# department.sub_departments.create(name: 'Отдел закупок')
# department.sub_departments.create(name: 'Отдел Автозаказа')
# department.sub_departments.create(name: 'Отдел продаж')
# department.sub_departments.create(name: 'Юридический отдел')
# department.sub_departments.create(name: 'Отдел кадров')

# Category.create(name: 'Монтажные работы', priority_id: 3)
# Category.create(name: 'Закупка, доставка ТМЦ', priority_id: 3)
# Category.create(name: 'Отопление', priority_id: 2)
# Category.create(name: 'Прочие работы', priority_id: 3)
# Category.create(name: 'Работы по кровли', priority_id: 3)
# Category.create(name: 'Работы по открытию ТО', priority_id: 3)
# Category.create(name: 'Работы по холоднильному оборудованию', priority_id: 3)
# Category.create(name: 'Ремонтно-регулировочные работы', priority_id: 1)
# Category.create(name: 'Сантехничеcкие работы', priority_id: 3)
# Category.create(name: 'Электричество, электрооборудование', priority_id: 3)

# cat1 = Category.find_by(name: 'Закупка, доставка ТМЦ')
# cat2 = Category.find_by(name: 'Монтажные работы')
# cat3 = Category.find_by(name: 'Отопление')
# cat4 = Category.find_by(name: 'Прочие работы')
# cat5 = Category.find_by(name: 'Работы по кровли')
# cat6 = Category.find_by(name: 'Работы по открытию ТО')
# cat7 = Category.find_by(name: 'Работы по холоднильному оборудованию')
# cat8 = Category.find_by(name: 'Ремонтно-регулировочные работы')
# cat9 = Category.find_by(name: 'Сантехничеcкие работы')
# cat10 = Category.find_by(name: 'Электричество, электрооборудование') 

# cat1.sub_categories.create(name: 'Закупка ТМЦ')
# cat1.sub_categories.create(name: 'Забрал ТМЦ для ремонта ХО')
# cat1.sub_categories.create(name: 'Доставка раскладушки')
# cat1.sub_categories.create(name: 'Доставка чайника')
# cat1.sub_categories.create(name: 'Доставка микроволновой печи')
# cat1.sub_categories.create(name: 'Забрал весы и обогреватель в офис')
# cat1.sub_categories.create(name: 'Доставка весов')
# cat1.sub_categories.create(name: 'Доставка у.з. отпугивателя от мышей')

# cat2.sub_categories.create(name: 'Частичный демонтаж и монтаж стеллажа')
# cat2.sub_categories.create(name: 'Демонтаж крепления шаров')
# cat2.sub_categories.create(name: 'Демонтаж деревянной конструкции и перемещение на мусорку')
# cat2.sub_categories.create(name: 'Сборка и монтаж кассового блока')

# cat3.sub_categories.create(name: 'Ревизия и запуск отопления')
# cat3.sub_categories.create(name: 'Подключение, опрессовка отопительной системы')

# cat4.sub_categories.create(name: 'Замена батареек на звонке')
# cat4.sub_categories.create(name: 'Спецзадание')
# cat4.sub_categories.create(name: 'Замена режимки')
# cat4.sub_categories.create(name: 'Инкассация')
# cat4.sub_categories.create(name: 'Подключение монитора на кассе')
# cat4.sub_categories.create(name: 'Заменил термометры')
# cat4.sub_categories.create(name: 'Замена психрометров')
# cat4.sub_categories.create(name: 'Закрепил терминал кассы')

# cat5.sub_categories.create(name: 'Ревизия крыши поиск мест протечки кровли')
# cat6.sub_categories.create(name: 'Работы по открытию')

# cat7.sub_categories.create(name: 'Пусконаладочные работы')
# cat7.sub_categories.create(name: 'Ремонт магнитных фиксаторов ХО')
# cat7.sub_categories.create(name: 'Ремонт ручки ХО')
# cat7.sub_categories.create(name: 'Ревизия ХО')
# cat7.sub_categories.create(name: 'Ремонт электропитания ХО')
# cat7.sub_categories.create(name: 'Выявление причины некорректной работы ХО')
# cat7.sub_categories.create(name: 'Ремонт контроллера')
# cat7.sub_categories.create(name: 'Перенастройка контроллера')
# cat7.sub_categories.create(name: 'Ревизия дренажной системы ХО')
# cat7.sub_categories.create(name: 'Чистка дренажной системы ХО')
# cat7.sub_categories.create(name: 'Ремонт дренажной системы ХО')
# cat7.sub_categories.create(name: 'Ремонт створок ХО')
# cat7.sub_categories.create(name: 'Ремонт ХО')
# cat7.sub_categories.create(name: 'Устранение посторонних шумов ХО')
# cat7.sub_categories.create(name: 'Разморозка испарителя')
# cat7.sub_categories.create(name: 'Чистка поддона и дренажа холодильной горки')
# cat7.sub_categories.create(name: 'Поиск утечки фреона')

# cat8.sub_categories.create(name: 'Регулировка доводчика')
# cat8.sub_categories.create(name: 'Ремонт газоотводящей трубы')
# cat8.sub_categories.create(name: 'Замена напольной плитки')
# cat8.sub_categories.create(name: 'Ремонт поддона')
# cat8.sub_categories.create(name: 'Ремонт двери склада')
# cat8.sub_categories.create(name: 'Ремонт горячего стола')
# cat8.sub_categories.create(name: 'Ремонт стула')
# cat8.sub_categories.create(name: 'Ремонт пола')
# cat8.sub_categories.create(name: 'Утепление задней двери')
# cat8.sub_categories.create(name: 'Ремонт двери на складе')
# cat8.sub_categories.create(name: 'Замена урны')
# cat8.sub_categories.create(name: 'Замена фасадной плитки')
# cat8.sub_categories.create(name: 'Регулировка доводчика входной двери')
# cat8.sub_categories.create(name: 'Замена замочной личинки двери')
# cat8.sub_categories.create(name: 'Ремонт доводчика входной двери')

# cat9.sub_categories.create(name: 'Ревизия бочка унитаза')
# cat9.sub_categories.create(name: 'Устранение засора раковины')
# cat9.sub_categories.create(name: 'Ревизия смывного бочка')
# cat9.sub_categories.create(name: 'Ревизия по затоплению')
# cat9.sub_categories.create(name: 'Чистка сифона')
# cat9.sub_categories.create(name: 'Монтаж клапана в канализационной трубе')

# cat10.sub_categories.create(name: 'Замена светильников,  потолочных светильников')
# cat10.sub_categories.create(name: 'Переключение питающей линии')
# cat10.sub_categories.create(name: 'Электромонтажные работы')
# cat10.sub_categories.create(name: 'Замена вводного автомата')
# cat10.sub_categories.create(name: 'Ревизия по электрики')
# cat10.sub_categories.create(name: 'Монтаж уличного освещения')
# cat10.sub_categories.create(name: 'Переделка питающей линии для подключения холодильника')
# cat10.sub_categories.create(name: 'Устранение электрических неполадок в сети магазина')
# cat10.sub_categories.create(name: 'Ревизия щитовой на предмет лишнего оборудования')
# cat10.sub_categories.create(name: 'Правил подсветку над ларями')

# department = Department.find_by(name: 'Торговый объект')

# Division.create(name: 'Авангардная-171', department: department, address: 'г.Казань, ул. Авангардная, д.171', email: 'shop@mail.ru')
# Division.create(name: 'Азина-101 (Киндери)', department: department, address: 'г.Казань, п. Киндери, ул. Азина, д.101', email: 'shop@mail.ru')
# Division.create(name: 'Азата Аббасова-8', department: department, address: 'г.Казань, ул. Азата Аббасова, д.8', email: 'shop@mail.ru')
# Division.create(name: 'Ак. Королева-22А', department: department, address: 'г.Казань, ул. Академика Королева, д.22А', email: 'shop@mail.ru')
# Division.create(name: 'Актайская-17', department: department, address: 'г.Казань, ул. Актайская, д.17', email: 'shop@mail.ru')
# Division.create(name: 'Аланлык СНТ', department: department, address: 'Высокогорский р-н, Аланлык, тер. СНТ, 2', email: 'shop@mail.ru')
# Division.create(name: 'Аметьевская-41А', department: department, address: 'г.Казань, ул. Аметьевская, д.41А', email: 'shop@mail.ru')
# Division.create(name: 'Амирхана-25', department: department, address: 'г.Казань, ул. Амирхана, д.25', email: 'shop@mail.ru')
# Division.create(name: 'Батыршина-27', department: department, address: 'г.Казань, ул. Батыршина, д.27', email: 'shop@mail.ru')
# Division.create(name: 'Батыршина-38', department: department, address: 'г.Казань, ул. Батыршина, д.38', email: 'shop@mail.ru')
# Division.create(name: 'Белинского-17', department: department, address: 'г.Казань, ул. Белинского, д.17', email: 'shop@mail.ru')
# Division.create(name: 'Южная-34А (Бирюли)', department: department, address: 'Высокогорский р-н, д.Старые Бирюли ул. Южная, д.34А', email: 'shop@mail.ru')
# Division.create(name: 'Блюхера-4', department: department, address: 'г.Казань, ул. Блюхера, д.4', email: 'shop@mail.ru')
# Division.create(name: 'Боевая-120', department: department, address: 'г.Казань, ул. Боевая, д.120', email: 'shop@mail.ru')
# Division.create(name: 'Болотникова-5', department: department, address: 'г.Казань, ул. Болотникова, д.5', email: 'shop@mail.ru')
# Division.create(name: 'Болотникова-11', department: department, address: 'г.Казань, ул. Болотникова, д.11', email: 'shop@mail.ru')
# Division.create(name: 'Булгар-1Б (Белое-Безводное)', department: department, address: 'Зеленодольский р-н, с.п.Раифский, с.Белое-Безводное, ул. Булгар, зд.1Б/1', email: 'shop@mail.ru')
# Division.create(name: 'Бондаренко-15', department: department, address: 'г.Казань, ул. Бондаренко, д.15', email: 'shop@mail.ru')
# Division.create(name: 'Восстания-27', department: department, address: 'г.Казань, ул. Восстания, д.27', email: 'shop@mail.ru')
# Division.create(name: 'Восстания-104', department: department, address: 'г.Казань, ул. Восстания, д.104', email: 'shop@mail.ru')
# Division.create(name: 'Восстания-111', department: department, address: 'г.Казань, ул. Восстания, д.111', email: 'shop@mail.ru')
# Division.create(name: 'Восстания-119Б', department: department, address: 'г.Казань, ул. Восстания, д.119Б', email: 'shop@mail.ru')
# Division.create(name: 'Гагарина-2', department: department, address: 'г.Казань, ул. Гагарина, д.2', email: 'shop@mail.ru')
# Division.create(name: 'Гагарина-14', department: department, address: 'г.Казань, ул. Гагарина, д.14', email: 'shop@mail.ru')
# Division.create(name: 'Гагарина-47', department: department, address: 'г.Казань, ул. Гагарина, д.47', email: 'shop@mail.ru')
# Division.create(name: 'Гагарина-48', department: department, address: 'г.Казань, ул. Гагарина, д.48', email: 'shop@mail.ru')
# Division.create(name: 'Галеева-5', department: department, address: 'г.Казань, ул. Галеева, д.5', email: 'shop@mail.ru')
# Division.create(name: 'Гвардейская-61А', department: department, address: 'г.Казань, ул. Гвардейская, д.61А', email: 'shop@mail.ru')
# Division.create(name: 'Беломорская-71/1', department: department, address: 'г.Казань, ул. Беломорская, д.71/1', email: 'shop@mail.ru')
# Division.create(name: 'Гудованцева-43', department: department, address: 'г.Казань, ул. Гудованцева, д.43', email: 'shop@mail.ru')
# Division.create(name: '25 лет Октября-4', department: department, address: 'г.Казань, ул. 25 лет Октября, д.4', email: 'shop@mail.ru')
# Division.create(name: 'Декабристов-108А', department: department, address: 'г.Казань, ул. Декабристов, д.108А', email: 'shop@mail.ru')
# Division.create(name: 'Краснококшайская-127', department: department, address: 'г.Казань, ул. Краснококшайская, д.127', email: 'shop@mail.ru')
# Division.create(name: 'Дружбы-56А (Дубровка)', department: department, address: 'Зеленодольский р-н, п.Дубровка, ул. Дружбы, д.56А', email: 'shop@mail.ru')
# Division.create(name: 'Железнодорожников-27/33 (Юдино)', department: department, address: 'г.Казань, п.Юдино, ул. Железнодорожников, д.27/33', email: 'shop@mail.ru')
# Division.create(name: 'Заводская-1А (Васильево)', department: department, address: 'Зеленодольский р-н, пгт.Васильево, ул. Заводская, д.1А', email: 'shop@mail.ru')
# Division.create(name: 'Закиева-41', department: department, address: 'г.Казань, ул. Закиева, д.41', email: 'shop@mail.ru')
# Division.create(name: 'Ибрагимова-19', department: department, address: 'г.Казань, ул. Ибрагимова, д.19', email: 'shop@mail.ru')
# Division.create(name: 'Ибрагимова-34', department: department, address: 'г.Казань, ул. Ибрагимова, д.34', email: 'shop@mail.ru')
# Division.create(name: 'Ильича-19 (Юдино)', department: department, address: 'г.Казань, п.Юдино, ул. Ильича, д.19', email: 'shop@mail.ru')
# Division.create(name: 'Исаева-14', department: department, address: 'г.Казань, ул. Исаева, д.14', email: 'shop@mail.ru')
# Division.create(name: 'Клары Цеткин-33', department: department, address: 'г.Казань, ул. Клары Цеткин, д.33', email: 'shop@mail.ru')
# Division.create(name: 'Кожевенная-28', department: department, address: 'г.Казань, ул. Кожевенная, д.28', email: 'shop@mail.ru')
# Division.create(name: 'Колхозная-42А (В.Гора)', department: department, address: 'Высокогорский р-н, п.Высокая Гора, ул. Колхозная, д.42А', email: 'shop@mail.ru')
# Division.create(name: 'Кооперативная-6 (В.Гора)', department: department, address: 'Высокогорский р-н, п.Высокая Гора, Кооперативная, д.6', email: 'shop@mail.ru')
# Division.create(name: 'Кооперативная-24 (В.Гора)', department: department, address: 'Высокогорский р-н, п.Высокая Гора, ул. Кооперативная, д.24', email: 'shop@mail.ru')
# Division.create(name: 'Короленко-32', department: department, address: 'г.Казань, ул. Короленко, д.32', email: 'shop@mail.ru')
# Division.create(name: 'Короленко-113', department: department, address: 'г.Казань, ул. Короленко, д.113', email: 'shop@mail.ru')
# Division.create(name: 'Космонавтов-57 (Васильево)', department: department, address: 'Зеленодольский р-н, пгт.Васильево, ул. Космонавтов, д.57', email: 'shop@mail.ru')
# Division.create(name: 'Краснококшайская-166', department: department, address: 'г.Казань, ул. Краснококшайская, д.166', email: 'shop@mail.ru')
# Division.create(name: 'Кулагина-8', department: department, address: 'г.Казань, ул. Кулагина, д.8', email: 'shop@mail.ru')
# Division.create(name: 'Кулахметова-4', department: department, address: 'г.Казань, ул. Кулахметова, д.4', email: 'shop@mail.ru')
# Division.create(name: 'Кулахметова-7', department: department, address: 'г.Казань, ул. Кулахметова, д.7', email: 'shop@mail.ru')
# Division.create(name: 'Кулахметова-17', department: department, address: 'г.Казань, ул. Кулахметова, д.17', email: 'shop@mail.ru')
# Division.create(name: 'Кулахметова-22', department: department, address: 'г.Казань, ул. Кулахметова, д.22', email: 'shop@mail.ru')
# Division.create(name: 'Кутузова-15', department: department, address: 'г.Казань, ул. Кутузова, д.15', email: 'shop@mail.ru')
# Division.create(name: 'Лагерная-22А (Васильево)', department: department, address: 'Зеленодольский р-н, пгт.Васильево, ул. Лагерная, д.22А', email: 'shop@mail.ru')
# Division.create(name: 'Ледяная-46А', department: department, address: 'г.Казань, ул. Ледяная, д.46А', email: 'shop@mail.ru')
# Division.create(name: 'Литвинова-80А', department: department, address: 'г.Казань, ул. Литвинова, д.80А', email: 'shop@mail.ru')
# Division.create(name: 'Липатова-5', department: department, address: 'г.Казань, ул. Липатова, д.5', email: 'shop@mail.ru')
# Division.create(name: 'Луговая-5М (В.Гора)', department: department, address: 'Высокогорский р-н, п.Высокая Гора, ул. Луговая, д.5М', email: 'shop@mail.ru')
# Division.create(name: 'Лушникова-1', department: department, address: 'г.Казань, ул. Лушникова, д.1', email: 'shop@mail.ru')
# Division.create(name: 'Мавлютова-46', department: department, address: 'г.Казань, ул. Мавлютова, д.46', email: 'shop@mail.ru')
# Division.create(name: 'Можайского-4', department: department, address: 'г.Казань, ул. Можайского, д.4', email: 'shop@mail.ru')
# Division.create(name: 'Можайского-12', department: department, address: 'г.Казань, ул. Можайского, д.12', email: 'shop@mail.ru')
# Division.create(name: 'Молодежная-1А (Нармонка)', department: department, address: 'Лаишевский р-н, с.Нармонка, ул. Молодежная, д.1А', email: 'shop@mail.ru')
# Division.create(name: 'Молодежная 2-я-36М (В.Гора)', department: department, address: 'Высокогорский р-н, п.Высокая Гора, ул. Молодежная 2-я, д.36М', email: 'shop@mail.ru')
# Division.create(name: 'Ново-Светлая-22', department: department, address: 'г.Казань, ул. Ново-Светлая, д.22', email: 'shop@mail.ru')
# Division.create(name: 'Ново-Юдинская-67А (Юдино)', department: department, address: 'г.Казань, п.Юдино, ул. Ново-Юдинская, д.67А', email: 'shop@mail.ru')
# Division.create(name: 'Новоселья-11', department: department, address: 'г.Казань, ул. Новоселья, д.11', email: 'shop@mail.ru')
# Division.create(name: 'Ноксинский спуск-20Б', department: department, address: 'г.Казань, ул. Ноксинский спуск, д.20Б', email: 'shop@mail.ru')
# Division.create(name: 'Окольная-23', department: department, address: 'г.Казань, ул. Окольная, д.23', email: 'shop@mail.ru')
# Division.create(name: 'Октябрьская-8А (П.Ковали)', department: department, address: 'Лаишевский р-н, с.Песчаные Ковали, ул. Октябрьская, д.8А', email: 'shop@mail.ru')
# Division.create(name: 'Октябрьская-1', department: department, address: 'г.Казань, ул. Октябрьская, д.1', email: 'shop@mail.ru')
# Division.create(name: 'Патриса Лумумбы-47', department: department, address: 'г.Казань, ул. Патриса Лумумбы, д.47', email: 'shop@mail.ru')
# Division.create(name: 'Первомайская-2А (п.Октябрьская)', department: department, address: 'Зеленодольский р-н, п.Октябрьский, ул. Первомайская, д.2А', email: 'shop@mail.ru')
# Division.create(name: 'Пионерская-20 (Тенишево)', department: department, address: 'Камско-Устьинский р-н, пгт.Тенишевот, ул. Пионерская, д.20', email: 'shop@mail.ru')
# Division.create(name: 'Политехническая-11 (Юдино)', department: department, address: 'г.Казань, п.Юдино, ул. Политехническая, д.11', email: 'shop@mail.ru')
# Division.create(name: 'Поперечно-Базарная-57', department: department, address: 'г.Казань, ул. Поперечно-Базарная, д.57', email: 'shop@mail.ru')
# Division.create(name: 'Поперечно-Кукушкинская-11', department: department, address: 'г.Казань, ул. Поперечно-Кукушкинская, д.11', email: 'shop@mail.ru')
# Division.create(name: 'Рахимова-8', department: department, address: 'г.Казань, ул. Рахимова, д.8', email: 'shop@mail.ru')
# Division.create(name: 'Революционная-73А (Юдино)', department: department, address: 'г.Казань, п.Юдино, ул. Революционная, д.73А', email: 'shop@mail.ru')
# Division.create(name: 'Сабан-1', department: department, address: 'г.Казань, ул. Сабан, д.1', email: 'shop@mail.ru')
# Division.create(name: 'Светлая-24', department: department, address: 'г.Казань, ул. Светлая, д.24', email: 'shop@mail.ru')
# Division.create(name: 'Светлая-27 (Ореховка)', department: department, address: 'Зеленодольский р-н, с.п.Октябрьское, д.Ореховка, ул. Светлая, д.27', email: 'shop@mail.ru')
# Division.create(name: 'Серова-3', department: department, address: 'г.Казань, ул. Серова, д.3', email: 'shop@mail.ru')
# Division.create(name: 'Серова-13', department: department, address: 'г.Казань, ул. Серова, д.13', email: 'shop@mail.ru')
# Division.create(name: 'Серова-6', department: department, address: 'г.Казань, ул. Серова, д.6', email: 'shop@mail.ru')
# Division.create(name: 'Серова-35', department: department, address: 'г.Казань, ул. Серова, д.35', email: 'shop@mail.ru')
# Division.create(name: 'Советская-82 (Кадышево)', department: department, address: 'г.Казань, п.Кадышево, ул. Советская, д.82', email: 'shop@mail.ru')
# Division.create(name: 'Стахановская-72 (Васильево)', department: department, address: 'Зеленодольский р-н, пгт.Васильево, ул. Стахановская, д.72', email: 'shop@mail.ru')
# Division.create(name: 'Стационная 3-я-59', department: department, address: 'г.Казань, ул. Стационная 3-я, д.59', email: 'shop@mail.ru')
# Division.create(name: 'Таежная-1', department: department, address: 'г.Казань, ул. Таежная, д.1', email: 'shop@mail.ru')
# Division.create(name: 'Тополевая-2', department: department, address: 'г.Казань, ул. Тополевая, д.2', email: 'shop@mail.ru')
# Division.create(name: 'Тунакова-50', department: department, address: 'г.Казань, ул. Тунакова, д.50', email: 'shop@mail.ru')
# Division.create(name: 'Урицкого-24', department: department, address: 'г.Казань, ул. Урицкого, д.24', email: 'shop@mail.ru')
# Division.create(name: 'Фрунзе-1', department: department, address: 'г.Казань, ул. Фрунзе, д.1', email: 'shop@mail.ru')
# Division.create(name: 'Фрунзе-9', department: department, address: 'г.Казань, ул. Фрунзе, д.9', email: 'shop@mail.ru')
# Division.create(name: 'Халезова-18', department: department, address: 'г.Казань, ул. Халезова, д.18', email: 'shop@mail.ru')
# Division.create(name: 'Халтурина-8', department: department, address: 'г.Казань, ул. Халтурина, д.8', email: 'shop@mail.ru')
# Division.create(name: 'Хлебозаводская-7Б', department: department, address: 'г.Казань, ул. Хлебозаводская, д.7Б', email: 'shop@mail.ru')
# Division.create(name: 'Центральная-1 (Салмачи)', department: department, address: 'г.Казань, п.Салмачи, ул. Центральная, д.1', email: 'shop@mail.ru')
# Division.create(name: 'Центральная-25 (Березовка)', department: department, address: 'Высокогорский р-н, п.Березовка ул. Центральная, д.25', email: 'shop@mail.ru')
# Division.create(name: 'Центральная-45/2 (Рождествено)', department: department, address: 'Лаишевский р-н, с.Рождествено, ул. Центральная, д.45/2', email: 'shop@mail.ru')
# Division.create(name: 'Центрально-Мариупольская-59', department: department, address: 'г.Казань, ул. Центрально-Мариупольская, д.59', email: 'shop@mail.ru')
# Division.create(name: 'Чапаева-26', department: department, address: 'г.Казань, ул. Чапаева, д.26', email: 'shop@mail.ru')
# Division.create(name: 'Чистопольская-53', department: department, address: 'г.Казань, ул. Чистопольская, д.53', email: 'shop@mail.ru')
# Division.create(name: 'Черноморская-3', department: department, address: 'г.Казань, ул. Черноморская, д.3', email: 'shop@mail.ru')
# Division.create(name: 'Чкалова-2', department: department, address: 'г.Казань, ул. Чкалова, д.2', email: 'shop@mail.ru')
# Division.create(name: 'Чуйкова-87А', department: department, address: 'г.Казань, ул. Чуйкова, д.87А', email: 'shop@mail.ru')
# Division.create(name: 'Шамиля Усманова-13', department: department, address: 'г.Казань, ул. Шамиля Усманова, д.13', email: 'shop@mail.ru')
# Division.create(name: 'Шамиля Усманова-35', department: department, address: 'г.Казань, ул. Шамиля Усманова, д.35', email: 'shop@mail.ru')
# Division.create(name: 'Шоссейная-2 (Борисоглебск)', department: department, address: 'г.Казань, п.Борисоглебск, ул. Шоссейная, д.2', email: 'shop@mail.ru')
# Division.create(name: 'Шоссейная-19', department: department, address: 'г.Казань, ул. Шоссейная, д.19', email: 'shop@mail.ru')
# Division.create(name: 'Татарстан-52 (МЭМ)', department: department, address: 'г.Казань, ул. Татарстан, д.52', email: 'shop@mail.ru')
# Division.create(name: 'Центральная-25 (МЭМ) (Чернышевка)', department: department, address: 'Высокогорский р-н, с.п.Чернышевское, д.Чернышевка, ул. Центральная, д.25', email: 'shop@mail.ru')
# Division.create(name: 'Маршальская-25 (МЭМ) ', department: department, address: 'г.Казань, ул. Маршальская, д.25', email: 'shop@mail.ru')

Mission.all.each do |mission|
  mission.execution_limit_at = mission.execution_limit_at.end_of_day if mission.execution_limit_at.present?
  mission.close_at = mission.close_at.end_of_day if mission.close_at.present?
  mission.save
end

MissionExecutor.all.each do |mission_executor|
  mission_executor.limit_at = mission_executor.limit_at.end_of_day if mission_executor.limit_at.present?
  mission_executor.close_at = mission_executor.close_at.end_of_day if mission_executor.close_at.present?
  mission_executor.save
end